package com.charan.stepstreak.utils

object Constants {
    val lowProgressMessages = listOf(
        "Let's move! 🚶‍♂️",
        "Start strong 💪",
        "Take the first step 👣",
        "Get up, go! 🏃",
        "A little push 🌀",
        "Time to hustle 🔥",
        "Don't wait, move ⏳",
        "Every step counts 📊",
        "Step into it 👟",
        "You got this 🙌",
        "Start your streak 🌟",
        "Move it now ⏱️",
        "Break the ice ❄️",
        "Shake it off 💃",
        "Just begin 🆕",
        "Tap into motion 🎯",
        "No zero days 🚫",
        "Today is yours 🗓️",
        "Ready, set, go! 🏁",
        "Push the start ▶️",
        "Small steps, big dreams 🌠",
        "One step closer 🏞️",
        "Keep the energy flowing ⚡",
        "Start your journey 🚶‍♀️",
        "Momentum starts now 🌀",
        "Take charge today 🏋️",
        "Every step is progress 📈",
        "Move forward with purpose 🎯"
    )
    val midProgressMessages = listOf(
        "Halfway there! 🟰",
        "Keep it up! 👍",
        "Stay on track 🛤️",
        "Crushing it! 🧨",
        "Almost there 🧗",
        "Stay focused 🎯",
        "Eyes on goal 👀",
        "You're getting close 🏃‍♀️",
        "Keep pushing 🚀",
        "Momentum's on 🔄",
        "Streak's alive 💥",
        "Push through! 📈",
        "Stay consistent ⏲️",
        "Just a bit more 💫",
        "You're doing it 🙌",
        "Close the gap ⚡",
        "Final push! 🏋️",
        "Almost finished 🎉",
        "You’ve come far 🛣️",
        "Don’t stop now ⛔",
        "Keep climbing 🧗‍♂️",
        "Focus on the finish 🏁",
        "You're unstoppable 🚀",
        "Keep the streak alive 🔥"
    )
    val highProgressMessages = listOf(
        "Great job! 🌟",
        "Well done! 👏",
        "Streak secured 🔐",
        "Goal smashed 💥",
        "You nailed it 🔨",
        "Steps crushed 🦶",
        "Champion mode 🏆",
        "Victory walk 🥇",
        "You’re on fire 🔥",
        "All done! ✅",
        "Awesome effort 🙌",
        "You did it! 🎉",
        "Killing it! 💣",
        "Crushed it 💪",
        "Mission complete 🎯",
        "Top form! 🧠",
        "Peak performance ⛰️",
        "Total win 🏅",
        "Smashed goals 🚀",
        "Perfection! 💯",
        "Legendary effort 🏅",
        "Unstoppable force 🌟",
        "Master of steps 👑",
        "Epic win 🎆"
    )
    val brokenStreakMessages = listOf(
        "Start fresh 🌱",
        "New day, go! 🌞",
        "Reset & rise 🔄",
        "Begin again 🔁",
        "Fresh streak 🌈",
        "Reboot time 💡",
        "Bounce back 🏀",
        "Clean slate 📃",
        "Start clean 🧼",
        "Let’s restart 🔃",
        "Go again 🏃",
        "Rise up ⬆️",
        "Restart now ⚡",
        "No shame, go 🙅",
        "Reclaim it! 🏹",
        "Get back up ⛹️",
        "Try again 🔁",
        "Today's new! 🆕",
        "No giving up 🚫",
        "New streak time 🕒",
        "Fresh energy 🌟",
        "Reignite the fire 🔥",
        "Start over strong 💪",
        "New chapter begins 📖"
    )
    val ongoingStreakMessages = listOf(
        "Keep going ➡️",
        "Streak strong 💪",
        "Don't stop now 🛑",
        "Keep momentum 🔁",
        "You're rolling 🌀",
        "Day by day 📅",
        "Stay streaky 🧬",
        "Next day wins 🥇",
        "One more day ☝️",
        "Fuel the streak ⛽",
        "Step by step 👣",
        "Build the habit 🏗️",
        "Never miss twice ✌️",
        "Daily fire 🔥",
        "You're on track 🛤️",
        "Win today too 🏆",
        "Daily victory 🎖️",
        "Keep the fire 🔥",
        "Stack the days 📚",
        "Unstoppable now 💥",
        "Consistency is key 🔑",
        "Every day matters 📆",
        "Keep the streak alive 🔄",
        "One day at a time 🕒"
    )
    val rebuildingStreakMessages = listOf(
        "Back at it! 🎯",
        "Let’s rebuild 🧱",
        "Fresh grind! 🌀",
        "New streak day 🗓️",
        "Great restart! 🔁",
        "Keep stepping 👟",
        "Back in game 🕹️",
        "New goals now 🥅",
        "Fresh start win 🏁",
        "Reboot success! 🖥️",
        "Day one strong ☝️",
        "Restart right! ✔️",
        "On the move 🛣️",
        "Momentum rising 📈",
        "One down again 🔂",
        "Strong comeback! 🛡️",
        "Let's go again ♻️",
        "Back in motion 🚶",
        "Step one done ✅",
        "Off to start 🚀",
        "Reclaim your streak 🏆",
        "New day, new chance 🌅",
        "Rise stronger 💪",
        "Fresh start, fresh goals 🎯"
    )
    val walkingMotivationMessages = listOf(
        "One step at a time 👣",
        "Walk with purpose 🎯",
        "Keep stepping forward ➡️",
        "Stride with pride 💃",
        "Miles begin with steps 🛤️",
        "Step into progress 🚶‍♀️",
        "Walking clears the mind 🧘",
        "Strong steps, strong mind 💪",
        "Move. Breathe. Walk. 🌬️",
        "Let’s take a walk 🌳",
        "Walking fuels the soul 🔥",
        "Power in each step ⚡",
        "Stay in motion 🔄",
        "Walk your way strong 🏞️",
        "Steps lead to strength 🦵",
        "Step up your day ☀️",
        "Your feet got this 🦶",
        "Flow with every step 🌊",
        "Small steps, big impact 💥",
        "Walking wins the day 🏆",
        "Every step matters 🌟",
        "Walk to greatness 🏔️",
        "Feel the rhythm 🎵",
        "Walking is winning 🏅"
    )
}